/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bj.ifri.master1.fenetres.enseignant;

import bj.ifri.master1.fenetres.filiere.*;
import bj.ifri.master1.emploi.modele.Dao;
import bj.ifri.master1.emploi.modele.Filiere;
import bj.ifri.master1.emploi.modele.Matiere;
import bj.ifri.master1.fenetres.*;
import bj.ifri.master1.fenetres.matiere.FormMatiere;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author imandine
 */
public class FormEnseignant extends javax.swing.JFrame  {
    
    private String mode /*modification , creation*/ ;
    private static Filiere courant;

    /**
     * Creates new form parametres
     */
    public FormEnseignant() {
        initComponents();
    }

    public FormEnseignant(String mode) {
        this.mode = mode;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        initComponents();
        
        remplirMatieres();
    }
    
    public FormEnseignant(String mode, Filiere filiere) {
        
        this.courant = filiere;
        this.mode = mode;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        
        initComponents();
         if("modification".equals(mode)){
            code.setText(filiere.getCode());
            code.setEnabled(false);
            libelle.setText(filiere.getLibelle());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
 regenerated by the FormEnseignant Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        libelle = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        libelle1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        libelle2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        libelle3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        libelle4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        matiere = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("matricule :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        jLabel2.setText("Nom:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        getContentPane().add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 100, -1));
        getContentPane().add(libelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 340, -1));

        jButton3.setText("Enregistrer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));
        getContentPane().add(libelle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 350, -1));

        jLabel3.setText("Prenom:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        getContentPane().add(libelle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 160, -1));

        jLabel4.setText("titre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));
        getContentPane().add(libelle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 350, -1));

        jLabel5.setText("Téléphone");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        getContentPane().add(libelle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 350, -1));

        jLabel6.setText("Adresse :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "code", "libelle"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 530, 170));

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, -1));

        getContentPane().add(matiere, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 310, -1));

        jLabel7.setText("Ajouter une matière .");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 140, -1));

        jButton2.setText("-");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 40, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Enregistrement des enseignants");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PHOTO");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 90));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        if( "".equals( code.getText().trim()) ){
            JOptionPane.showMessageDialog(this, "Le code de la filiere est obligatoire");
            return;
        }
        if( "".equals( libelle.getText().trim()) ){
            JOptionPane.showMessageDialog(this, "Le libelle de la filiere est obligatoire");
            return;
        }
        
        switch(mode){
            case "creation" : 
                try {
                    // TODO add your handling code here:
                    Dao.Connect();
                    Connection connection = Dao.getConnection();

                    String query = "INSERT INTO \"ENSEIGNANT\" VALUES(?,?)";
                    PreparedStatement pst = connection.prepareStatement(query);
                    pst.setString(1, code.getText());
                    pst.setString(2, libelle.getText());
                    int result = pst.executeUpdate();
                } catch (SQLException ex) {
                    Logger.getLogger(FormEnseignant.class.getName()).log(Level.SEVERE, null, ex);
                }   
                break;
            case "modification": 
                try {
                Dao.Connect();
                Connection connection = Dao.getConnection();
                    String query = "UPDATE \"ENSEIGNANT\" SET NOM = ? WHERE CODE = ?";
                    PreparedStatement pst = connection.prepareStatement(query);
                    pst.setString(2, code.getText());
                    pst.setString(1, libelle.getText());
                    int result = pst.executeUpdate();
                } catch (SQLException ex) {
                    Logger.getLogger(FormEnseignant.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
        }
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String selected = matiere.getSelectedItem().toString();
        String[] splited = selected.split(":");
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        int nbre = model.getRowCount();
        for( int i = 0; i < nbre; i++ ){
            String code = table.getValueAt(i, 0).toString();
            if( code.equals(splited[0])) return;
        }
        model.addRow( splited);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEnseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEnseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEnseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEnseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEnseignant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField code;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField libelle;
    private javax.swing.JTextField libelle1;
    private javax.swing.JTextField libelle2;
    private javax.swing.JTextField libelle3;
    private javax.swing.JTextField libelle4;
    private javax.swing.JComboBox<String> matiere;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private void remplirMatieres() {
        
        
         DefaultComboBoxModel model = new DefaultComboBoxModel<>();
        Statement st = null;
        ResultSet rs = null;
        try {
            Dao.Connect();
            Connection connection = Dao.getConnection();
            String query = "SELECT * FROM \"MATIERE\"";
            st = connection.createStatement();
            rs = st.executeQuery(query);
            while( rs.next()){
                model.addElement(new Matiere(rs.getString("code"), rs.getString("libelle")));
            }
            matiere.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(FormMatiere.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            try{
            rs.close();
            st.close();
            }catch(Exception e){
            }
        }
    }
}
