/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bj.ifri.master1.fenetres.salle;

import bj.ifri.master1.emploi.modele.Dao;
import bj.ifri.master1.emploi.modele.Salle;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author imandine
 */
public class FormSalle extends javax.swing.JFrame  {
    
    private String mode /*modification , creation*/ ;
    private static Salle courant;

    /**
     * Creates new form parametres
     */
    public FormSalle() {
        initComponents();
    }

    public FormSalle(String mode) {
        this.mode = mode;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        initComponents();
    }
    
    public FormSalle(String mode, Salle salle) {
        
        this.courant = salle;
        this.mode = mode;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        
        initComponents();
         if("modification".equals(mode)){
            code.setText(salle.getCode());
            code.setEnabled(false);
            libelle.setText(salle.getLibelle());
            localisation.setText(salle.getLocalisation());
            capacite.setText("" + salle.getCapacite());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
 regenerated by the FormSalle Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        libelle = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        localisation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        capacite = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Code");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setText("Libellé");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        getContentPane().add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 80, -1));
        getContentPane().add(libelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 320, -1));

        jButton3.setText("Enregistrer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));
        getContentPane().add(localisation, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 330, -1));

        jLabel3.setText("Localisation :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        getContentPane().add(capacite, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 70, -1));

        jLabel5.setText("Capacité :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Gestion des salles");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        if( "".equals( code.getText().trim()) ){
            JOptionPane.showMessageDialog(this, "Le code est obligatoire");
            return;
        }
        if( "".equals( libelle.getText().trim()) ){
            JOptionPane.showMessageDialog(this, "Le libelle est obligatoire");
            return;
        }
        if( "".equals( localisation.getText().trim()) ){
            JOptionPane.showMessageDialog(this, "La loclisation est obligatoire");
            return;
        }
        if( "".equals( capacite.getText().trim()) ){
            JOptionPane.showMessageDialog(this, "La capacite est obligatoire");
            return;
        }
        
        switch(mode){
            case "creation" : 
                try {
                    // TODO add your handling code here:
                    Dao.Connect();
                    Connection connection = Dao.getConnection();

                    String query = "INSERT INTO \"SALLE\" VALUES(?,?,?,?)";
                    PreparedStatement pst = connection.prepareStatement(query);
                    pst.setString(1, code.getText());
                    pst.setString(2, libelle.getText());
                    pst.setString(3, localisation.getText());
                    pst.setInt(4, Integer.parseInt(capacite.getText()));
                    int result = pst.executeUpdate();
                } catch (SQLException ex) {
                    Logger.getLogger(FormSalle.class.getName()).log(Level.SEVERE, null, ex);
                }   
                break;
            case "modification": 
                try {
                Dao.Connect();
                Connection connection = Dao.getConnection();
                    String query = "UPDATE \"SALLE\" SET libelle = ?, localisation=?, capacite = ? WHERE code = ?";
                    PreparedStatement pst = connection.prepareStatement(query);
                    pst.setString(2, libelle.getText());
                    pst.setString(3, localisation.getText());
                    pst.setInt(4, Integer.parseInt(capacite.getText()));
                    pst.setString(1, code.getText());
                    int result = pst.executeUpdate();
                } catch (SQLException ex) {
                    Logger.getLogger(FormSalle.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
        }
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField capacite;
    private javax.swing.JTextField code;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField libelle;
    private javax.swing.JTextField localisation;
    // End of variables declaration//GEN-END:variables

}
